### ISSUE TITLE
sourceMappingURLPrefix?

### ISSUE THREAD

**Issue by KrunchMuffin** [ismriv/gulp-rollbar#3]
All my maps have the full path, what is this going to do? In the RB API it states minified_url which is the full path to the resource. Is this the same thing?

**Comment by mbrevda** [comment]
Yes,[ its the same thing](https://github.com/ismriv/gulp-rollbar/blob/master/index.js#L53).

**Comment by ismriv** [comment]
Fixed by https://github.com/ismriv/gulp-rollbar/pull/4

**Comment by mbrevda** [comment]
I take this back, it seems that urls ARE important, sourcemaps wont work without them. #4 should probably be reverted
